export default function getReceiveOptions (RECEIVE_OPTIONS = DEFAULT_RECEIVE_OPTIONS) {
  return {
    AttributeNames: RECEIVE_OPTIONS.ATTRIBUTE_NAMES || DEFAULT_RECEIVE_OPTIONS.ATTRIBUTE_NAMES,
    MaxNumberOfMessages: RECEIVE_OPTIONS.MAX_NUMBER_OF_MESSAGES || DEFAULT_RECEIVE_OPTIONS.MAX_NUMBER_OF_MESSAGES,
    MessageAttributeNames: RECEIVE_OPTIONS.MESSAGE_ATTRIBUTE_NAMES || DEFAULT_RECEIVE_OPTIONS.MESSAGE_ATTRIBUTE_NAMES,
    VisibilityTimeout: RECEIVE_OPTIONS.VISIBILITY_TIMEOUT || DEFAULT_RECEIVE_OPTIONS.VISIBILITY_TIMEOUT,
    WaitTimeSeconds: RECEIVE_OPTIONS.WAIT_TIME_SECONDS || DEFAULT_RECEIVE_OPTIONS.WAIT_TIME_SECONDS
  }
}

export const DEFAULT_RECEIVE_OPTIONS = {
  ATTRIBUTE_NAMES: ['All'],
  MAX_NUMBER_OF_MESSAGES: 10,
  MESSAGE_ATTRIBUTE_NAMES: ['All'],
  VISIBILITY_TIMEOUT: 30,
  WAIT_TIME_SECONDS: 0
}
